2025-01-17 16:18:36,260 - ERROR - Token validation failed: Token is invalid or expired
2025-01-17 16:18:36,280 - ERROR - Internal Server Error: /accounts/test/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/rest_framework_simplejwt/backends.py", line 139, in decode
    return jwt.decode(
           ~~~~~~~~~~^
        token,
        ^^^^^^
    ...<8 lines>...
        },
        ^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/jwt/api_jwt.py", line 222, in decode
    decoded = self.decode_complete(
        jwt,
    ...<8 lines>...
        leeway=leeway,
    )
  File "/usr/local/lib/python3.13/site-packages/jwt/api_jwt.py", line 156, in decode_complete
    decoded = api_jws.decode_complete(
        jwt,
    ...<3 lines>...
        detached_payload=detached_payload,
    )
  File "/usr/local/lib/python3.13/site-packages/jwt/api_jws.py", line 220, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jwt/api_jws.py", line 328, in _verify_signature
    raise InvalidSignatureError("Signature verification failed")
jwt.exceptions.InvalidSignatureError: Signature verification failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/rest_framework_simplejwt/tokens.py", line 56, in __init__
    self.payload = token_backend.decode(token, verify=verify)
                   ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework_simplejwt/backends.py", line 154, in decode
    raise TokenBackendError(_("Token is invalid or expired")) from ex
rest_framework_simplejwt.exceptions.TokenBackendError: Token is invalid or expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/accounts/views.py", line 330, in get
    refresh = RefreshToken(refresh_token)
  File "/usr/local/lib/python3.13/site-packages/rest_framework_simplejwt/tokens.py", line 58, in __init__
    raise TokenError(_("Token is invalid or expired"))
rest_framework_simplejwt.exceptions.TokenError: Token is invalid or expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/accounts/views.py", line 333, in get
    response.delete_cookie('refreshToken')
    ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
2025-01-17 16:22:07,760 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:22:11,057 - ERROR - Token validation failed: Token is invalid or expired
2025-01-17 16:22:11,058 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:22:23,691 - WARNING - Unauthorized: /accounts/tokencheck/
2025-01-17 16:22:23,941 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:22:24,127 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 16:22:24,128 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:22:24,632 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 16:22:42,165 - INFO - buraya girdim invalid token
2025-01-17 16:22:42,166 - INFO - User edamar authenticated successfully.
2025-01-17 16:22:43,012 - INFO - buraya girdim invalid token
2025-01-17 16:22:43,013 - INFO - User edamar authenticated successfully.
2025-01-17 16:22:43,253 - INFO - buraya girdim invalid token
2025-01-17 16:22:43,254 - INFO - User edamar authenticated successfully.
2025-01-17 16:22:43,485 - INFO - buraya girdim invalid token
2025-01-17 16:22:43,485 - INFO - User edamar authenticated successfully.
2025-01-17 16:22:45,546 - INFO - buraya girdim invalid token
2025-01-17 16:22:45,547 - INFO - User edamar authenticated successfully.
2025-01-17 16:22:47,441 - INFO - buraya girdim invalid token
2025-01-17 16:22:47,442 - INFO - User edamar authenticated successfully.
2025-01-17 16:22:52,162 - INFO - buraya girdim invalid token
2025-01-17 16:22:52,163 - INFO - User edamar authenticated successfully.
2025-01-17 16:22:56,922 - INFO - buraya girdim invalid token
2025-01-17 16:22:56,923 - INFO - User edamar authenticated successfully.
2025-01-17 16:22:59,342 - INFO - buraya girdim invalid token
2025-01-17 16:22:59,343 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:23:15,993 - ERROR - Token validation failed: Token is invalid or expired
2025-01-17 16:23:15,994 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:24:04,370 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:24:07,989 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:24:13,716 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:34:31,817 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:36:15,232 - INFO - /app/pong_game/settings.py changed, reloading.
2025-01-17 16:36:32,796 - WARNING - No refresh token provided.
2025-01-17 16:36:32,796 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:36:36,046 - WARNING - No refresh token provided.
2025-01-17 16:36:36,046 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:36:36,333 - WARNING - No refresh token provided.
2025-01-17 16:36:36,333 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:36:36,479 - WARNING - No refresh token provided.
2025-01-17 16:36:36,479 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:36:41,105 - WARNING - No refresh token provided.
2025-01-17 16:36:41,105 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:36:44,894 - WARNING - No refresh token provided.
2025-01-17 16:36:44,894 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:36:45,040 - WARNING - No refresh token provided.
2025-01-17 16:36:45,041 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:36:45,165 - WARNING - No refresh token provided.
2025-01-17 16:36:45,165 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:36:45,285 - WARNING - No refresh token provided.
2025-01-17 16:36:45,285 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:36:46,908 - WARNING - Unauthorized: /accounts/tokencheck/
2025-01-17 16:36:47,197 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:36:47,473 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 16:36:47,474 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:36:47,971 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 16:38:36,617 - WARNING - Unauthorized: /accounts/tokencheck/
2025-01-17 16:38:36,754 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:38:36,904 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 16:38:36,906 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:38:37,431 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 16:38:40,325 - WARNING - Unauthorized: /accounts/tokencheck/
2025-01-17 16:38:40,456 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:38:40,593 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 16:38:40,594 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:38:41,003 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 16:39:42,589 - ERROR - Token validation failed: Token is invalid or expired
2025-01-17 16:39:42,591 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:39:42,833 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:39:43,071 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 16:39:43,073 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:39:43,533 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 16:40:47,206 - WARNING - No access token provided.
2025-01-17 16:40:57,832 - ERROR - Token validation failed: Token is invalid or expired
2025-01-17 16:40:57,833 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:40:57,975 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:40:58,229 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 16:40:58,230 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:40:58,640 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 16:48:12,039 - INFO - /app/pong_game/settings.py changed, reloading.
2025-01-17 16:48:50,547 - INFO - /app/pong_game/settings.py changed, reloading.
2025-01-17 16:49:05,314 - WARNING - No refresh token provided.
2025-01-17 16:49:05,315 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:49:05,514 - WARNING - No refresh token provided.
2025-01-17 16:49:05,514 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:49:05,955 - WARNING - No refresh token provided.
2025-01-17 16:49:05,955 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:49:06,191 - WARNING - No refresh token provided.
2025-01-17 16:49:06,191 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:49:13,441 - WARNING - No refresh token provided.
2025-01-17 16:49:13,441 - WARNING - Unauthorized: /accounts/test/
2025-01-17 16:49:13,743 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:49:14,026 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 16:49:14,027 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 16:49:14,442 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 16:50:36,383 - INFO - buraya girdim invalid token
2025-01-17 16:50:36,384 - INFO - User edamar authenticated successfully.
2025-01-17 16:50:54,232 - INFO - buraya girdim invalid token
2025-01-17 16:50:54,233 - INFO - User edamar authenticated successfully.
2025-01-17 16:51:42,719 - WARNING - No access token provided.
2025-01-17 16:52:20,925 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:53:23,878 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:53:28,766 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:53:36,459 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:53:43,203 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:54:34,402 - WARNING - No access token provided.
2025-01-17 16:54:34,402 - INFO - Generating access token...
2025-01-17 16:55:12,954 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:55:36,484 - INFO - /app/pong_game/settings.py changed, reloading.
2025-01-17 16:55:50,503 - INFO - User edamar authenticated successfully.
2025-01-17 16:55:54,032 - INFO - User edamar authenticated successfully.
2025-01-17 16:55:55,456 - INFO - User edamar authenticated successfully.
2025-01-17 16:55:58,174 - INFO - User edamar authenticated successfully.
2025-01-17 16:56:07,460 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:56:11,013 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:56:17,580 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:56:20,112 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:56:21,982 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:56:22,015 - WARNING - Unauthorized: /accounts/get_profile/
2025-01-17 16:56:51,602 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:56:56,137 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:57:37,318 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:57:43,381 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:57:56,152 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:57:57,825 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 16:58:03,501 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:58:07,823 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:58:08,496 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:58:09,025 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:58:10,476 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:58:22,339 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:58:32,943 - INFO - /app/pong_game/settings.py changed, reloading.
2025-01-17 16:58:35,630 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:58:43,104 - INFO - User edamar authenticated successfully.
2025-01-17 16:58:54,374 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 16:59:14,994 - INFO - {'detail': errordetail(string='given token not valid for any token type', code='token_not_valid'), 'code': errordetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': errordetail(string='accesstoken', code='token_not_valid'), 'token_type': errordetail(string='access', code='token_not_valid'), 'message': errordetail(string='token is invalid or expired', code='token_not_valid')}]}
2025-01-17 17:02:31,743 - WARNING - No refresh token provided.
2025-01-17 17:02:31,744 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:02:39,678 - WARNING - No refresh token provided.
2025-01-17 17:02:39,679 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:02:40,067 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:02:40,410 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 17:02:40,411 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:02:40,861 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 17:02:51,774 - WARNING - No refresh token provided.
2025-01-17 17:02:51,774 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:02:52,015 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:02:52,251 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 17:02:52,252 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:02:52,732 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 17:02:57,368 - WARNING - No refresh token provided.
2025-01-17 17:02:57,369 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:03:16,449 - WARNING - No refresh token provided.
2025-01-17 17:03:16,449 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:03:16,586 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:03:16,725 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 17:03:16,726 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:03:17,132 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 17:03:50,421 - WARNING - No refresh token provided.
2025-01-17 17:03:50,422 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:04:17,555 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 17:04:19,433 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 17:04:25,137 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 17:04:26,795 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 17:04:28,429 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 17:04:33,863 - WARNING - No refresh token provided.
2025-01-17 17:04:33,882 - ERROR - Internal Server Error: /accounts/test/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/accounts/views.py", line 325, in get
    response.delete_cookie('accessToken')
    ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
2025-01-17 17:04:36,906 - WARNING - No refresh token provided.
2025-01-17 17:04:36,921 - ERROR - Internal Server Error: /accounts/test/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/accounts/views.py", line 325, in get
    response.delete_cookie('accessToken')
    ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
2025-01-17 17:05:00,592 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 17:05:05,194 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 17:05:06,825 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 17:05:09,529 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 17:05:11,139 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 17:05:17,880 - INFO - /app/accounts/views.py changed, reloading.
2025-01-17 17:05:21,278 - WARNING - No refresh token provided.
2025-01-17 17:05:21,279 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:05:37,854 - WARNING - No refresh token provided.
2025-01-17 17:05:37,855 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:05:38,004 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:05:38,140 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 17:05:38,141 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:05:38,715 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 17:06:09,808 - WARNING - No refresh token provided.
2025-01-17 17:06:09,808 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:06:27,722 - INFO - /app/pong_game/settings.py changed, reloading.
2025-01-17 17:06:36,842 - INFO - /app/pong_game/settings.py changed, reloading.
2025-01-17 17:06:46,178 - WARNING - No refresh token provided.
2025-01-17 17:06:46,179 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:06:46,420 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:06:46,668 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 17:06:46,669 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:06:47,121 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 17:07:55,078 - ERROR - Token validation failed: Token is invalid or expired
2025-01-17 17:07:55,078 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:07:55,219 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:07:55,411 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 17:07:55,412 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:07:55,988 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 17:08:35,975 - WARNING - No refresh token provided.
2025-01-17 17:08:35,975 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:08:40,966 - WARNING - No refresh token provided.
2025-01-17 17:08:40,967 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:08:41,216 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:08:41,373 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 17:08:41,374 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:08:41,837 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 17:11:43,960 - ERROR - Token validation failed: Token is invalid or expired
2025-01-17 17:11:43,961 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:11:45,523 - WARNING - No refresh token provided.
2025-01-17 17:11:45,523 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:11:45,792 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:11:45,927 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 17:11:45,928 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:11:46,360 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 17:28:22,129 - WARNING - No refresh token provided.
2025-01-17 17:28:22,129 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:28:22,421 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:28:22,691 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 17:28:22,692 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:28:23,218 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 17:29:31,663 - ERROR - Token validation failed: Token is invalid or expired
2025-01-17 17:29:31,663 - WARNING - Unauthorized: /accounts/test/
2025-01-17 17:29:31,915 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:29:32,144 - DEBUG - https://api.intra.42.fr:443 "POST /oauth/token HTTP/1.1" 200 None
2025-01-17 17:29:32,146 - DEBUG - Starting new HTTPS connection (1): api.intra.42.fr:443
2025-01-17 17:29:32,601 - DEBUG - https://api.intra.42.fr:443 "GET /v2/me HTTP/1.1" 200 None
2025-01-17 17:29:48,922 - INFO - /app/pong_game/settings.py changed, reloading.
2025-01-17 17:29:52,933 - INFO - /app/pong_game/settings.py changed, reloading.
2025-01-17 17:29:58,654 - INFO - /app/pong_game/settings.py changed, reloading.
2025-01-17 17:30:37,186 - INFO - User edamar authenticated successfully.
2025-01-17 17:32:14,549 - INFO - User edamar authenticated successfully.
2025-01-17 17:38:53,821 - INFO - /app/pong_game/settings.py changed, reloading.
2025-01-17 17:39:01,287 - INFO - /app/pong_game/settings.py changed, reloading.
2025-01-17 17:41:18,563 - INFO - User edamar authenticated successfully.
2025-01-17 17:43:12,190 - INFO - User edamar authenticated successfully.
2025-01-17 17:44:22,468 - INFO - User edamar authenticated successfully.
